import { gallerySessionPrompt } from "../../shared/gallery.ts"
export function galleryAiPage(base: string, directory: string, description: string) {
  const prompt = gallerySessionPrompt().replaceAll(
    "ainize-agents",
    "node /home/aincode/agents/.ainize-tools/ainize-agents.mjs",
  )
  const data = JSON.stringify({ base, directory, prompt, description }).replaceAll("<", "\\u003c")
  return `<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Uncommon Gallery · AI Builder</title><style>body{font:16px system-ui;background:#f6f5f1;color:#242822}main{max-width:720px;margin:60px auto;padding:24px}textarea{box-sizing:border-box;width:100%;min-height:200px;padding:16px;font:inherit;border:1px solid #bbc7bd;border-radius:10px}button{background:#286047;color:white;padding:12px 24px;border:0;border-radius:8px;margin-top:16px;cursor:pointer}a{color:#286047}</style><main><a href="${base}/gallery">Uncommon Gallery</a><h1>AI와 에이전트 만들기</h1><p>원하는 역할과 동작을 설명하세요. AI가 필요한 내용을 물어보고, 에이전트 파일을 작성하며 실제 응답을 테스트합니다.</p><label for="description">어떤 에이전트를 만들거나 수정할까요?</label><textarea id="description"></textarea><button id="start">AinCode 대화 시작</button><p id="status" role="status"></p></main><script>const data=${data};document.getElementById('description').value=data.description;document.getElementById('start').onclick=async()=>{const button=document.getElementById('start'),status=document.getElementById('status'),description=document.getElementById('description').value;if(!description.trim()){status.textContent='에이전트의 역할을 설명해주세요.';return}button.disabled=true;status.textContent='AinCode 대화를 여는 중…';try{const headers={'content-type':'application/json','x-opencode-directory':data.directory};const create=await fetch(data.base+'/session',{method:'POST',headers,body:JSON.stringify({title:'Uncommon Gallery Builder'})});if(!create.ok)throw Error('대화를 열 수 없습니다. 로그인과 작업공간 상태를 확인해주세요.');const session=await create.json();const sent=await fetch(data.base+'/session/'+session.id+'/prompt_async',{method:'POST',headers,body:JSON.stringify({system:data.prompt,parts:[{type:'text',text:description}]})});if(!sent.ok)throw Error('AI 대화를 시작할 수 없습니다.');location.href=data.base+'/'+btoa(data.directory).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')+'/session/'+session.id}catch(e){status.textContent=e.message;button.disabled=false}};</script></html>`
}
